;Is the traffic periodic (cyclic)? 1 for Yes 0 for No 
; periodic=1

; Choose traffic application class from the following list;
; 1- Open/Closed (Distributed) Control Loop and Motion Control - Zero Jitter
; 2- Open/Closed (Distributed) Control Loop and Motion Control  
; 3- Factory Automation and Non Synchronized Control            
; 4- Control Events and Alarms                                  
; 5- Voice/Video                                                
; 6- Network Control and Inter-network Control                  
; 7- Operator Commands and HMI Interactions                                        
; 8- Configuration and Management                               
; 9- Diagnostics and Monitoring                                                                 
; 10- Best Effort                                                
; traffic_application_class=1

[Flow1]
flow_id=F1
periodic=1
traffic_application_class=1